# Generated by Django 5.0.7 on 2024-07-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', models.CharField(max_length=250)),
                ('blog_date', models.DateField()),
            ],
            options={
                'db_table': 'BlogTable',
            },
        ),
    ]
