# Generated by Django 5.0.7 on 2024-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogreviews',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_review_title', models.CharField(max_length=50)),
                ('blog_review_desc', models.CharField(max_length=250)),
                ('blog_review_date', models.DateField()),
            ],
            options={
                'db_table': 'BlogReviewTable',
            },
        ),
    ]
